name: ✏️ Edit channel
description: Request to edit channel description
title: 'Edit: '
labels: ['channels:edit']

body:
  - type: input
    attributes:
      label: Channel ID (required)
      description: The ID of the channel that should be updated
      placeholder: 'AnhuiTV.cn'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        What exactly needs to be changed?

  - type: input
    attributes:
      label: Channel Name
      description: "Official channel name in English or call sign. May include: `a-z`, `0-9`, `space`, `-`, `!`, `:`, `&`, `.`, `+`, `'`, `/`, `»`, `#`, `%`, `°`, `$`, `@`, `?`"
      placeholder: 'Anhui TV'

  - type: input
    attributes:
      label: Alternative Names
      description: List of alternative channel names separated by `;`. May contain any characters except `,` and `"`
      placeholder: '安徽卫视'

  - type: input
    attributes:
      label: Network
      description: Network of which this channel is a part. May contain any characters except `,` and `"`
      placeholder: 'Anhui'

  - type: input
    attributes:
      label: Owners
      description: List of channel owners separated by `;`. May contain any characters except `,` and `"`
      placeholder: 'China Central Television'

  - type: input
    attributes:
      label: Country
      description: Country code from which the channel is transmitted. A list of all supported countries and their codes can be found in [data/countries.csv](https://github.com/iptv-org/database/blob/master/data/countries.csv) 
      placeholder: 'CN'

  - type: input
    attributes:
      label: Subdivision
      description: Code of the subdivision (e.g., provinces or states) from which the broadcast is transmitted. A list of all supported subdivisions and their codes can be found in [data/subdivisions.csv](https://github.com/iptv-org/database/blob/master/data/subdivisions.csv)
      placeholder: 'CN-AH'

  - type: input
    attributes:
      label: City
      description: Name of the city from which the channel is transmitted
      placeholder: 'Hefei'

  - type: input
    attributes:
      label: Broadcast Area
      description: List of codes describing the broadcasting area of the channel separated by `;`. Any combination of `r/<region_code>`, `c/<country_code>`, `s/<subdivision_code>`
      placeholder: 's/CN-AH'

  - type: input
    attributes:
      label: Languages
      description: List of languages in which the channel is broadcast separated by `;`. A list of all supported languages and their codes can be found in [data/languages.csv](https://github.com/iptv-org/database/blob/master/data/languages.csv)
      placeholder: 'zho;eng'

  - type: input
    attributes:
      label: Categories
      description: List of categories to which this channel belongs separated by `;`. A list of all supported categories can be found in [data/categories.csv](https://github.com/iptv-org/database/blob/master/data/categories.csv)
      placeholder: 'animation;kids'

  - type: dropdown
    attributes:
      label: NSFW
      description: Indicates whether the channel broadcasts adult content
      options:
        - 'FALSE'
        - 'TRUE'
    validations:
      required: true

  - type: input
    attributes:
      label: Launched
      description: Launch date of the channel (`YYYY-MM-DD`)   
      placeholder: '2016-07-28'

  - type: input
    attributes:
      label: Closed
      description: Date on which the channel closed (`YYYY-MM-DD`)   
      placeholder: '2020-05-31'

  - type: input
    attributes:
      label: Replaced By
      description: The ID of the channel that this channel was replaced by
      placeholder: 'CCTV1.cn'

  - type: input
    attributes:
      label: Website
      description: Official website URL
      placeholder: 'http://www.ahtv.cn/'

  - type: input
    attributes:
      label: Logo
      description: "Logo URL. Only URL with HTTPS protocol are allowed. Supported image types: `PNG`, `JPEG`. Max size: 512x512 pixels. The link should not be [geo-blocked](https://en.wikipedia.org/wiki/Geo-blocking)"
      placeholder: 'https://example.com/logo.png'

  - type: textarea
    attributes:
      label: Notes
      description: 'Anything else we should know?'
